### ISSUE TITLE
Unable to handle long urls?

### ISSUE THREAD

**Issue by dvillaveces-tq** [danielchalef/mrfparse#14]
I tried running using `-i https://bcbstn.mrf.bcbs.com/2023-02_430_65B0_in-network-rates.json.gz?&Expires=1679603554&Signature=muqMLyEWOLPz9gheiGv1RUGMcrU2e~C4zUwuH2H5Xtbic8wh1oByCq2u7DmiW3WIpNVrHpS~UaXSiP8UFqsKlPfh5Z8ISUe0p9mhwrFuVDy48~3TrLnppa~uc0kckLx2uxY8XUXLw2ocHe7gJ4OsLTZwYPa1Tq0le7WwA48fLYeROgb0ZrDh7BcaeHHY0INC3KLX2dyB4TJSgu2~uaamMCHnDaDXhIswhGTjKxdNmbTwPy03THkvT8LxpJpiyh3~TanIdmPqSjP9IXdJEOnKpyAs32yOQptH7IvpwpKnRULtJwzbyfbJQB-39i21tT4wYCvcj3E1E7eTJJT6CouZ5A__&Key-Pair-Id=K27TQMT39R1C8A` but got the following error:

Fatal error in /app/pkg/mrfparse/pipeline/steps.go#116: open /tmp/mrfparse584609021/src/2023-02_430_65B0_in-network-rates.json.gz?&Expires=1679603554&Signature=muqMLyEWOLPz9gheiGv1RUGMcrU2e\~C4zUwuH2H5Xtbic8wh1oByCq2u7DmiW3WIpNVrHpS\~UaXSiP8UFqsKlPfh5Z8ISUe0p9mhwrFuVDy48\~3TrLnppa\~uc0kckLx2uxY8XUXLw2ocHe7gJ4OsLTZwYPa1Tq0le7WwA48fLYeROgb0ZrDh7BcaeHHY0INC3KLX2dyB4TJSgu2\~uaamMCHnDaDXhIswhGTjKxdNmbTwPy03THkvT8LxpJpiyh3~TanIdmPqSjP9IXdJEOnKpyAs32yOQptH7IvpwpKnRULtJwzbyfbJQB-39i21tT4wYCvcj3E1E7eTJJT6CouZ5A__&Key-Pair-Id=K27TQMT39R1C8A: file name too long

**Comment by danielchalef** [comment]
Pipeline functionality isn't as well tested as the constituent steps (see the `split` and `parse` commands). For a more resilient production architecture, I recommend downloading MRF files outside of the `mrfparse` and using Airflow or similar to manage the pipeline steps.

That said, this was a relatively easy fix: stripping the querystring from the path. Merged as #19
