### ISSUE TITLE
Error when parsing large file

### ISSUE THREAD

**Issue by dvillaveces-tq** [danielchalef/mrfparse#15]
I tried parsing a 17.8GB file but got an error:
`docker run -it -v "$(pwd)/tmp/mrf-parse:/tmp/mrf-parse:rw" dancarbone/danielchalef-mrfparse pipeline -i https://antm-pt-prod-dataz-nogbd-nophi-us-east1.s3.amazonaws.com/anthem/VA_GVHSMED0023.json.gz -o /tmp/mrf-parse/outputs -p -1 -s /tmp/mrf-parse/data/filters/tic_500_shoppable_svcs.csv`

INFO[2023-02-04T18:10:41Z] Running step: Download           
ERRO[2023-02-04T18:12:41Z] Fatal error in /app/pkg/mrfparse/pipeline/steps.go#121: context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by danielchalef** [comment]
See my comment on #14 about production use of `mrfparse`. I suggest using a more robust mechanism to download MRF files in production than what the `pipeline` command offers and using a pipeline orchestrator (such as airflow) to manage the data pipeline steps.

That said, increasing the `Client.Timeout` is fairly trivial. Would you like to submit a PR to do so?

**Comment by dvillaveces-tq** [comment]
Thanks for the reply. Sorry, I'm not the most technical person. I'll leave the PR to someone else.

**Comment by danielchalef** [comment]
I've increased the timeout to 10 minutes. See #20 . I'll merge this as soon as the tests pass.

**Comment by danielchalef** [comment]
Merged #20. To increase the timeout further, see https://github.com/danielchalef/mrfparse/blob/a40bc83b15975ad40ef5a275fbfbdda36c9e4246/pkg/mrfparse/http/http.go#L31

**Comment by danielchalef** [comment]
@dvillaveces-tq Client.Timeout is now configurable via `config.yaml` and defaults to 20 minutes.

See https://github.com/danielchalef/mrfparse#configuration-via-configyml-and-environment-variables

**Comment by dvillaveces-tq** [comment]
Great. Thank you!
