### ISSUE TITLE
Provider groups object not parsed

### ISSUE THREAD

**Issue by dvillaveces-tq** [danielchalef/mrfparse#17]
`docker run -it -v "$(pwd)/tmp/mrf-parse:/tmp/mrf-parse:rw"  dancarbone/danielchalef-mrfparse pipeline -i https://antm-pt-prod-dataz-nogbd-nophi-us-east1.s3.amazonaws.com/anthem/CA_ELRKMEDELRK.json.gz -o /tmp/mrf-parse/outputs -p -1 -s /tmp/mrf-parse/data/filters/tic_500_shoppable_svcs.csv`

Parsed successfully, but the provider groups object was not parsed, so I was not able to associate a rate with an NPI

**Comment by danielchalef** [comment]
I'm unable to dig in today to understand what's happening here. Would you like to take a look and provide a PR if you have a bugfix?

**Comment by danielchalef** [comment]
@dvillaveces-tq The only service listed in this small MRF is `billing_code` `0488T` (see below). This is not in the CMS' 500 shoppable services list that you're using as a service filter. As a result, the related `provider_groups` object is ignored. This is by design as we don't want to capture providers for whom we don't have related service pricing data.

```json
{
  "reporting_entity_name": "Anthem Blue Cross California",
  "reporting_entity_type": "Health Insurance Network",
  "last_updated_on": "2023-02-01",
  "version": "1.3.1",
  "provider_references": [
    {
      "provider_group_id": 40.0000000001,
      "provider_groups": [
        {
          "npi": [
            1114438157
          ],
          "tin": {
            "type": "npi",
            "value": "1114438157"
          }
        }
      ]
    }
  ],
  "in_network": [
    {
      "negotiation_arrangement": "ffs",
      "name": "PREVENTIVE BEHAVIOR CHANGE, ONLINE/ELECTRONIC STRUCTURED INTENSIVE PROGRAM FOR PREVENTION OF DIABETES USING A STANDARDIZ",
      "billing_code_type": "HCPCS",
      "billing_code_type_version": "2023",
      "billing_code": "0488T",
      "negotiated_rates": [
        {
          "provider_references": [
            40.0000000001
          ],
          "negotiated_prices": [
            {
              "negotiated_type": "fee schedule",
              "negotiated_rate": 93,
              "expiration_date": "9999-12-31",
              "service_code": [
                "11",
                "22"
              ],
              "billing_class": "professional"
            }
          ]
        }
      ]
    }
  ]
}
```
