### ISSUE TITLE
Pipeline error using local json file

### ISSUE THREAD

**Issue by larryclaman** [danielchalef/mrfparse#29]
I'm trying to use a file from a provider that I've already downloaded.  I can't get mrfparse to read this file.  Am I missing something obvious?

I'm trying:
`mrfparse pipeline -i oscar.json -o oscar.parq -p 99`

and the output is:
```
INFO[2024-11-18T14:29:45-05:00] Running step: Download
WARN[2024-11-18T14:29:51-05:00] Retrying in 6.4s after error Get "oscar.json": unsupported protocol scheme ""
WARN[2024-11-18T14:29:57-05:00] Retrying in 12.8s after error Get "oscar.json": unsupported protocol scheme ""
WARN[2024-11-18T14:30:10-05:00] Retrying in 25.6s after error Get "oscar.json": unsupported protocol scheme ""
```
which continues until it fails.

**Comment by danielchalef** [comment]
Thanks for reporting. I haven't worked with MRF files in several years, and unfortunately this repo is no longer maintained.

**Comment by larryclaman** [comment]
oh, ok.  thanks for responding regardless.
Would you mind archiving the repo so others know that it's no longer maintained?

**Comment by danielchalef** [comment]
Good point. Will do.
